### ISSUE TITLE
ImportError: DLL load failed while importing _greenlet: module was not found.

### ISSUE THREAD

**Issue by antowkas** [neumond/python-computer-craft#13]
How do I correct this error?
```
C:\home>python -m computercraft.server
Traceback (most recent call last):
  File "C:\Users\toxal\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\toxal\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\toxal\AppData\Local\Programs\Python\Python310\lib\site-packages\computercraft\server.py", line 8, in <module>
    from .sess import CCSession
  File "C:\Users\toxal\AppData\Local\Programs\Python\Python310\lib\site-packages\computercraft\sess.py", line 15, in <module>
    from greenlet import greenlet, getcurrent as get_current_greenlet
  File "C:\Users\toxal\AppData\Local\Programs\Python\Python310\lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: DLL load failed while importing _greenlet: module was not found.
```

**Comment by Garulf** [comment]
I've seen this error appear when someone uses a library that has compiled code built for one version of Python and you attempt to use it on different Python version.

**Comment by neumond** [comment]
You probably need to reinstall greenlet library. `python -m pip install --force-reinstall greenlet`
`python -c 'import greenlet; print("ok")'` should print ok.
If this probe prints ok, but server doesn't start anyway, feel free to open another issue here.
